sudo: false
language: ruby

rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head

before_install:
  - gem update --system

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email: false
