sudo: false
language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

env:
  - BUNDLE_VERSION="~> 1.0"
  - BUNDLE_VERSION="~> 2.0"

before_install:
  - gem update --system
  - gem uninstall --executables bundler
  - gem install bundler --version "$BUNDLE_VERSION"

script:
  - bundle exec rubocop --parallel
  - bundle exec rake

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head
